### ISSUE TITLE
Pretty printing and format issues

### ISSUE THREAD

**Issue by henrilouvin** [timstaley/voevent-parse#6]
The  `Voevent` function returns an `ObjectifiedElement` which cannot be properly pretty printed. This can easily be reproduced by printing the result of  `etree.tostring(v, pretty_print=True)` at the end of the function. This only affects the pretty printing of the whole voevent, and not the printing of a single element though.

**Comment by henrilouvin** [comment]
This is due to the presence of a carriage return in the `v2_0_skeleton_str` which the parser is unable to remove because it cannot decide whether or not this carriage return is useful data.
To prevent this issue, it is sufficient to edit the last two lines of the `v2_0_skeleton_str` definition from 
```
 93     ivorn="ivo://undefined">
 94 </voe:VOEvent>
```
to 
```
 93     ivorn="ivo://undefined">\
 94 </voe:VOEvent>
```
or even just
```
 93     ivorn="ivo://undefined"> </voe:VOEvent>
```

**Comment by henrilouvin** [comment]
Fixing this not only allows whole voevents to be pretty printed at any time using `vp.dumps`, but also for the dumped voevents to be nicely indented upon opening with almost any text software

**Comment by timstaley** [comment]
Thanks @henrilouvin, that's a good spot! A fix is now in master and I'll mint a new release soon.
