### ISSUE TITLE
Why.Description child does not appear to exist

### ISSUE THREAD

**Issue by andrewzwaniga** [timstaley/voevent-parse#7]
I have been following the tutorial on authoring a VOEvent, however it doesn't appear that Why.Description exists. 

`>>> v.Why.Description
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/objectify.pyx", line 230, in lxml.objectify.ObjectifiedElement.__getattr__
  File "src/lxml/objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: Description
`

**Comment by timstaley** [comment]
Hi Andrew,
thanks for the bug report! 
The examples on the docs-pages are generated from these scripts:
https://github.com/timstaley/voevent-parse/tree/master/examples

Both seem to run ok on my machine.
Can you try downloading and running 'author_new_voevent.py' from that folder and see if that works for you? If not, let me know if you get the same error and perhaps we can do some debugging.

If it doesn't work It might also be worth checking what version of LXML you have installed?
