### ISSUE TITLE
Remove colons from filename to enable pip install under Windows

### ISSUE THREAD

**Issue by klunko** [timstaley/voevent-parse#8]
In Windows a colon (':') is a reserved character so it can't be used in filenames.
There is one filename with colons in voevent-parse:
src/voeventparse/fixtures/MOA_Lensing_Event_2015-07-10T14:50:54.00.xml
The result is that "pip install" failed under Windows.
Could you please fix it.

**Comment by timstaley** [comment]
Hi @klunko, 
thanks for filing the issue, that's an unfortunate oversight. I maintain voevent-parse in my spare time so can't promise I'll get to this anytime soon, but it should be an easy fix and I'll sort it when I can. 

Alternatively if you'd like to have a go at making a pull-request to fix it up yourself, that would be super!

**Comment by timstaley** [comment]
Fixed in #10
